### ISSUE TITLE
My java script to extract the sections of a pdf does not work

### ISSUE THREAD

**Issue by MehmetAbdulhay** [BMKEG/lapdftext#23]

**Comment by MehmetAbdulhay** [comment]
Hello. I am using 

lapdftext-1.7.2-SNAPSHOT-jar-with-dependencies.jar

the java script is as below:

                File pdf = new File("C:\\LayoutAwarePDFText\\lapdftext-master\\dnm11.pdf");
                File outXmlFile = new File("C:\\LayoutAwarePDFText\\lapdftext-master\\dnm1.xml");
                File ruleFile = new File("C:\\LayoutAwarePDFText\\lapdftext-master\\dnm1.drl");
                //File ruleFile = new File("C:\\LayoutAwarePDFText\\lapdftext-master\\general.drl");
            
                LapdfEngine engine = new LapdfEngine();
                LapdfDocument lapdf = engine.blockifyPdfFile(pdf);
                
                engine.classifyDocument(lapdf, ruleFile);
                engine.writeSectionsToOpenAccessXmlFile(lapdf, outXmlFile);

The pdf file is plos biology article which is given as an example in lapdftext site. 20689801
AND drl file is also epoch_7Jun_8.drl. So as a result of my  code I got an error as below:

java.lang.ClassNotFoundException: Unable to find class 'ChunkBlock'
	at org.drools.base.ClassTypeResolver.resolveType(ClassTypeResolver.java:215)
	at org.drools.compiler.PackageBuilder.mergePackage(PackageBuilder.java:897)
	at org.drools.compiler.PackageBuilder.newPackage(PackageBuilder.java:871)
	at org.drools.compiler.PackageBuilder.addPackage(PackageBuilder.java:578)
	at org.drools.compiler.PackageBuilder.addPackageFromDrl(PackageBuilder.java:267)
	at org.drools.compiler.PackageBuilder.addKnowledgeResource(PackageBuilder.java:459)
	at org.drools.builder.impl.KnowledgeBuilderImpl.add(KnowledgeBuilderImpl.java:28)
	at edu.isi.bmkeg.lapdf.classification.ruleBased.RuleBasedChunkClassifier.<init>(RuleBasedChunkClassifier.java:83)
	at edu.isi.bmkeg.lapdf.controller.LapdfEngine.classifyDocument(LapdfEngine.java:334)
	at lapdftext.FirstTrial.<init>(FirstTrial.java:25)
	at lapdftext.FirstTrial.main(FirstTrial.java:45)
ERROR: edu.isi.bmkeg.lapdf.classification.ruleBased.RuleBasedChunkClassifier - GlobalError: chunkError importing : 'edu.isi.bmkeg.pdf.features.ChunkFeatures'Error importing : 'edu.isi.bmkeg.pdf.model.ChunkBlock'
INFO : edu.isi.bmkeg.lapdf.controller.LapdfEngine - Writing block-classified XML in OpenAccess format C:\LayoutAwarePDFText\lapdftext-master\dnm1.xml

What might be the problem?

Thanks in advance.

Kindest regards,
Mehmet
